import type { Builder } from '@/types'

export const BUILDERS: Builder[] = [
  {
    id: 'tsunami-guitars',
    slug: 'tsunami-guitars',
    shopName: 'Tsunami Guitars',
    location: 'Canada',
    speciality: 'Electric Guitars',
    bio: 'Founded by real instrument sellers. Builders of exceptional electric guitars and custom instruments. Every build is handcrafted to order.',
    rating: 4.9,
    reviewCount: 47,
    avgBuildWeeks: 8,
    verified: true,
    featured: true,
    avatar: 'TG',
    listingCount: 12,
  },
  {
    id: 'morrison-custom',
    slug: 'morrison-custom',
    shopName: 'J. Morrison Custom',
    location: 'Nashville, USA',
    speciality: 'Electric & Semi-Hollow',
    bio: 'Nashville-based luthier with 18 years building boutique electrics. Known for hand-carved archtops and single-cut solidbodies.',
    rating: 5.0,
    reviewCount: 31,
    avgBuildWeeks: 12,
    verified: true,
    featured: false,
    avatar: 'JM',
    listingCount: 8,
  },
  {
    id: 'nakamura-lutherie',
    slug: 'nakamura-lutherie',
    shopName: 'T. Nakamura Lutherie',
    location: 'Tokyo, Japan',
    speciality: 'Hollowbody & Archtop',
    bio: 'Japanese-trained luthier specialising in hollowbody jazz archtops and thinline electrics. Export worldwide.',
    rating: 4.8,
    reviewCount: 22,
    avgBuildWeeks: 16,
    verified: true,
    featured: false,
    avatar: 'TN',
    listingCount: 5,
  },
  {
    id: 'rossi-instruments',
    slug: 'rossi-instruments',
    shopName: 'A. Rossi Instruments',
    location: 'Florence, Italy',
    speciality: 'Orchestral & Acoustic',
    bio: 'Italian luthier with classical training. Master-grade violins, violas and acoustic guitars using traditional methods.',
    rating: 5.0,
    reviewCount: 18,
    avgBuildWeeks: 20,
    verified: true,
    featured: false,
    avatar: 'AR',
    listingCount: 6,
  },
  {
    id: 'chen-ukulele',
    slug: 'chen-ukulele',
    shopName: 'M. Chen Ukuleles',
    location: 'Honolulu, Hawaii',
    speciality: 'Ukuleles',
    bio: 'Third-generation Hawaiian ukulele builder. Specialises in Koa concert and tenor builds with abalone appointments.',
    rating: 4.9,
    reviewCount: 38,
    avgBuildWeeks: 6,
    verified: true,
    featured: false,
    avatar: 'MC',
    listingCount: 14,
  },
  {
    id: 'wright-acoustic',
    slug: 'wright-acoustic',
    shopName: 'Wright Acoustic Works',
    location: 'Portland, USA',
    speciality: 'Acoustic Guitars',
    bio: 'Pacific Northwest acoustic builder focused on sustainable tonewoods. OM, Dreadnought and 000 body styles.',
    rating: 4.7,
    reviewCount: 15,
    avgBuildWeeks: 14,
    verified: true,
    featured: false,
    avatar: 'WA',
    listingCount: 9,
  },
]

export const FEATURED_BUILDER = BUILDERS.find(b => b.featured)!
